# Containerfile
FROM python:3.13-slim

# Install system dependencies (optional, needed for many Python packages)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libsqlite3-dev \
    npm \
    libsqlite3-dev \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g @11ty/eleventy

# Set work directory inside container
WORKDIR /app

# Copy requirements and install Python deps
COPY .python/requirements.txt .python/requirements.txt
RUN pip install --upgrade pip && pip install -r .python/requirements.txt

COPY data/build ./data/build
COPY frontend/serve ./frontend/serve

RUN chmod +x data/build
RUN chmod +x frontend/serve

RUN cd frontend/
RUN npm install sqlite3
RUN cd ../

# Default command is bash shell
CMD ["bash", "./frontend/serve"]

